enum MenuButtonEnum {
  retraitArgent,
  paiementsAchats,
  depotArgent,
  bankToWaller,
  wallerToBank,
  transfertArgent,
  historiqueTransactions,
  abonnementTele,
  cartesBancaires,
  comptesBancaires,
  gabAProximite,
  restaurant,
  gaz,
  pressing,
  materiauxConstruction,
  fraisScolarite,
  loyer,
  jobs,
  pharmacie,
  brasserie,
  caves,
  parisSportifs,
  achatPass,
  achatUnite,
  locationVehicules,
  tontine,
  dons,
  cadeaux,
  vouchers,
  paiementTimbres,
  paimenentTaxes,
  paiementContravention,
  factureElectricite,
  factureEau,
  abonnementFibre,
  abonnementPeage,
  tickets,
  canalPlus,
  netflix,
  cinema,
  stade,
  concert,
  ticketBus,
  ticketTrain,
  billetAvion,
  hotels,
  rechargeYango,
  annulerTransfert,
  evenements,
  nounous,
}
  // voirPlus,
  // voirPlusCategorie,
  // envoyerVersMobile,
  // recevoirArgent,
  // bankEtMicrofinance,
  // cartesBancairesEtPrepayees,
  // lebedoo,
  // soldeHistorique,
  // paiementLoyer,
  // assurances,
  // job,
  // caves,
  // brasserie,
  // cadeau,
  // pressing,
  // gaz,
  // restaurants,
  // pharmacies,
  // constructionDeMaison,
  // locationDeVehicule,
  // achatDUnite,
  // achatdePasse,
  // factureElectricite,
  // factureEau,
  // don,
  // tontine,
  // abonnementPeage,
  // achatPass,
  // abonnementTele,
  // abonnementFibre,
  // scolarite,
  // parisCoursesDeChevaux,
  // laRouletteDeLebedoo,
  // lebedooJackpot,
  // parisSportifs,
  // betclic,
  // pmu,
  // oneXbet,
  // premierBet,
  // sportCash,
  // casinoCash,
  // googlePlayRecharge,
  // payementPrets,
  // pretScolarite,
  // bankToWallet,
  // playstationStore,
  // xboxStore,
  // nintendoStore,
  // appleStore,
  // steam,
  // virgin,
  // busEtCar,
  // ticketDeCinema,
  // evenements,
  // hotels,
  // billetDavion,
  // openDemat,
  // invertirAvec10kFcfa,
  // lebedooMoney,
  // bourseDinvestissement,
  // googlePlayStore,
  // carteBancairePrepayee,
